### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by kilkellym** [theBIMdev/RevitExtension#8]
The following references were missing from the Revit version projects:

PresentationCore
System.Drawing
WindowBase

**Comment by theBIMdev** [comment]
> I would also add:
> 
> PresentationFramework
> System.Xaml
> System.Windows.Forms

I think I may opt to make these 3 "Recommended Options" in the Project Setup Wizard, since not everyone will necessarily want windows forms built into their addin. I'm thinking of having a few checkboxes for things like "Support Windows Forms", and "Generate Post-Build Commands", etc.
